#!/bin/bash

CONFIG=/etc/dtmrepo.conf
eval `dtmrepo-globalconf $CONFIG`

REPOSDIR=`grep reposdir ${yumconf} | sed -r 's/ +//g' | cut -d= -f2`

LOCKDIR="/var/lock"
LOCKWAIT=30

LOGDIR='/var/log/dtmrepo'
LOGFILE="${LOGDIR}/dtmrepo.log"
[ ! -d "${LOGDIR}" ] && ( mkdir -p ${LOGDIR} || exit 1 )

UPDATE=0
GENREPO=0
VERBOSE=0
FORCE=0
SYNCALL=0
INITIALISE=0
AUTOFIX=0

ENTITLEMENTCERTDIR="/etc/pki/entitlement"
YUMREPOSDIR="/etc/yum.repos.d"
REDHATREPO="redhat.repo"
MASTERREPO="master.repo"
SMREPOCONF="${YUMREPOSDIR}/${REDHATREPO}"
MASTERREPOCONF="${YUMREPOSDIR}/${MASTERREPO}"
ISREGISTERED="Current"

LOCALMARKER="local:"

usage() {
    echo
    echo "Usage: `basename $0` [-adfgiruvx]"
    echo -e "\t-a: sync all packages in a repo (default: new packages only)."
    echo -e "\t-c: check the system for sanity"
    echo -e "\t-d: <distro,...>"
    echo -e "\t-f: force the operation"
    echo -e "\t-g: generate repodata"
    echo -e "\t-i: initialise and register the system"
    echo -e "\t-r: <repo,...>"
    echo -e "\t-u: update"
    echo -e "\t-v: verbose"
    echo -e "\t-x: automatically fix subscription problems"
    exit 1
}

fix_cert() {
    \rm ${ENTITLEMENTCERTDIR}/* &> /dev/null
    subscription-manager refresh
}

configure_master_repo() {
    subscription-manager config --rhsm.manage_repos=1
    yum repolist
    \mv ${SMREPOCONF} ${MASTERREPOCONF}
    subscription-manager config --rhsm.manage_repos=0
    sed -ri 's/enabled *= *1/enabled = 0/' ${MASTERREPOCONF}

    [ "${REPOSDIR}X" != "X" ] && ln -sf ${MASTERREPOCONF} ${REPOSDIR}/${MASTERREPO}
}

sanity_check() {
    SUBSERROR=0
    REPOERROR=0
    CERTERROR=0

    if [ "${subscribed}" -ne 1 ]; then
        [ -e ${REPOSDIR}/${MASTERREPO} ] && \rm ${REPOSDIR}/${MASTERREPO}

    else
        SMSTATUS=$(subscription-manager status|grep 'Overall Status'|awk '{print $NF}')
        [ "${SMSTATUS}" != "${ISREGISTERED}" ] && SUBSERROR=1
        [  ! -e "${MASTERREPOCONF}" ] && REPOERROR=1

        ls ${ENTITLEMENTCERTDIR}/*.pem &> /dev/null
        [ "$?" -ne 0 ] && CERTERROR=1
    fi

    [ "${SUBSERROR}" -eq 1 ] && echo "Subscription manager is set to active in ${CONFIG} but the system is not registered."
    [ "${REPOERROR}" -eq 1 ] && echo "${MASTERREPOCONF} is missing."
    [ "${CERTERROR}" -eq 1 ] && echo "Entitlement certificate(s) missing."

    [ "${SUBSERROR}" -eq 1 -o "${REPOERROR}" -eq 1 -o "${CERTERROR}" -eq 1 ] && exit 1

    return 0
}

initialise() {
    if [ "${subscribed}" -ne 1 ]; then
        echo "The configuration is not set to subscribe to Red Hat. Nothing to do here. Set the \"subscribed\" option in ${CONFIG} otherwise you are good to go."
        return 0
    fi

    SMSTATUS=$(subscription-manager status|grep 'Overall Status'|awk '{print $NF}')
    if [ "${SMSTATUS}" != "${ISREGISTERED}" ]; then
        read -p "Red Hat username: " USERNAME
        read -s -p "Red Hat password: " PASSWORD
        echo
        echo "Attempting to register the system using the provided credentials..."
        subscription-manager register --username=${USERNAME} --password=${PASSWORD} && subscription-manager attach --auto
        [ "$?" -ne 0 ] && exit 1
        echo "System registration successful."
    fi

    echo "Preparing master repo configuration."
    configure_master_repo
}

update_lock_error() {
    echo "Another update process has a lock on $1."
    exit 1
}

genrepo_lock_error() {
    echo "An update or createrepo process has a lock on $1."
    exit 1
}

update_repo() {
    _REPODIR=$1
    _REPOID=$2
    _DISTRO=$3
    _ARCH=$4
    _SYNCALL="-n"
    _QUIET="-q"
    _VERBOSE=""
    _YUMCONF=""

    if [ "${VERBOSE}" -eq 1 ]; then
        _VERBOSE="-v"
        _QUIET=""
    fi
    [ "${SYNCALL}" -eq 1 ] && _SYNCALL=""

    [ "${yumconf}X" != "X" ] && _YUMCONF="-c ${yumconf}"

    _LOCKFILE="${LOCKDIR}/${_DISTRO}-${_REPODIR}.lock"
    _DESTDIR="${rootdir}/${_DISTRO}/${_REPODIR}"

    if [ "${_REPOID:0:${#LOCALMARKER}}" == "${LOCALMARKER}" ]; then
        _SOURCEDIR=${_REPOID#${LOCALMARKER}}
        if [ ! -L "${_DESTDIR}" ]; then
            [ -d "${_DESTDIR}" ] && return 0
            [ "${_VERBOSE}" != "" ] && echo "Creating symlink for local source ${_SOURCEDIR}."
            \ln -s ${_SOURCEDIR} ${_DESTDIR} &> /dev/null
            if [ "$?" -ne 0 ]; then
                echo "Error creating symlink for local source ${_SOURCEDIR}."
                return 1
            fi
        elif [ ! -e "${_DESTDIR}" ]; then
            echo "Broken symlink found: ${_DESTDIR}."
            return 1
        fi
        return
    fi

    if [ ! -d "${_DESTDIR}" ]; then
        mkdir -p "${_DESTDIR}" &> /dev/null
        if [ "$?" -ne 0 ]; then
            echo "Error creating package repository ${_DESTDIR}."
            return 1
        fi
    fi

    (
    flock -w ${LOCKWAIT} 1001 || update_lock_error ${_DESTDIR}
    yum ${_YUMCONF} --disablerepo=* --enablerepo=${_REPOID} clean metadata
    reposync ${_QUIET} ${_YUMCONF} ${_SYNCALL} -r ${_REPOID} -a ${_ARCH} -p ${_DESTDIR}
    ) 1001> ${_LOCKFILE}
}

gen_repodata() {
    _REPODIR=$1
    _REPOID=$2
    _DISTRO=$3
    _FORCE="-C --update"
    _VERBOSE=""
    _PROTECT=" "

    [ "${FORCE}" -eq 1 ] && _FORCE=" "
    [ "${VERBOSE}" -eq 1 ] && _VERBOSE="-v"

    if [ "${protect}X" != "X" ]; then
        _PROTECT="$(echo ${protect} | sed -r 's/[ ,]+/|/g')"
    fi

    _LOCKFILE="${LOCKDIR}/${_DISTRO}-${_REPODIR}.lock"
    _DESTDIR="${rootdir}/$_DISTRO/$_REPODIR"

    if [ ! -d "${_DESTDIR}" ]; then
        echo "Repository directory ${_DESTDIR} for ${_DISTRO} does not exist."
        return 1
    fi

    (
    flock -w ${LOCKWAIT} 1001 || genrepo_lock_error ${_DESTDIR}
    if [ "${_REPOID:0:${#LOCALMARKER}}" == "${LOCALMARKER}" ]; then
        createrepo ${_FORCE} ${_VERBOSE} -s sha --simple-md-filenames --basedir ${_DESTDIR} -o ${_DESTDIR} ${_DESTDIR}
    else
        repomanage -c -o -k ${keep} ${_DESTDIR} | egrep -v "${_PROTECT}" | xargs rm -f
        createrepo ${_FORCE} ${_VERBOSE} -s sha --simple-md-filenames --basedir ${_DESTDIR} -o ${_DESTDIR} ${_DESTDIR}
    fi
    ) 1001> ${_LOCKFILE}

}

action() {
    if [ "${UPDATE}" -eq 1 ]; then
        [ "${VERBOSE}" -eq 1 ] && echo "Synchronising distro $3 repo $1."
        update_repo $1 $2 $3 $4
    fi

    if [ "${GENREPO}" -eq 1 ]; then
        [ "${VERBOSE}" -eq 1 ] && echo "Generating repodata for distro $3 repo $1."
        gen_repodata $1 $2 $3
    fi
}

process_distro_repo() {
# TDISTRO -- target distro
# TREPO -- target repo

    if [ "${TDISTRO}" != "" ]; then
        if [ ! -f "${confdir}/${TDISTRO}.conf" ]; then
            echo "${TDISTRO} has no configuration"
            exit 1
        else
            DISTROLIST="${TDISTRO}.conf"
        fi
    else
        DISTROLIST=$(for i in ${confdir}/*.conf; do basename $i; done)
    fi

    if [ "${DISTROLIST}" == "" ]; then
        if [ "${VERBOSE}" -eq 1 ]; then
            echo "Could not find any distribution configuration. Nothing to do here. Exiting."
        fi
        exit 0
    fi

    for DIST in ${DISTROLIST}; do
        eval $(dtmrepo-repoconf ${confdir}/${DIST})
        if [ "${#repostore[@]}" -eq 0 ]; then
            if [ "${VERBOSE}" -eq 1 ]; then
                echo "No repos defined for ${DIST%%\.conf}. Skipping..."
            fi
            continue
        fi

        NREPO=$(expr ${#repostore[@]} - 1)
        for i in $(seq 0 ${NREPO}); do
            if [ "${TREPO}" != "" ]; then
                if [ "${TREPO}" != "${repostore[$i]}" ]; then
                    continue
                else
                    _REPONAME=${reponame[$i]}
                    action ${TREPO} ${_REPONAME} ${DIST%%\.conf} ${arch}
                    break
                fi
            else
                _REPO=${repostore[$i]}
                _REPONAME=${reponame[$i]}
                action ${_REPO} ${_REPONAME} ${DIST%%\.conf} ${arch}
            fi
        done
    done
}

############################################################
# program start

REPO=""
REPOS=""
TREPO=""
DISTRO=""
DISTROS=""
TDISTRO=""
OPTERR=1
OPTIND=1

while getopts 'aifugvxr:d:' opt; do
    case "${opt}" in
        a)  SYNCALL=1
            ;;
        i)  INITIALISE=1
            ;;
        f)  FORCE=1
            ;;
        u)  UPDATE=1
            ;;
        g)  GENREPO=1
            ;;
        r)  REPO=${OPTARG}
            ;;
        d)  DISTRO=${OPTARG}
            ;;
        v)  VERBOSE=1
            ;;
        x)  AUTOFIX=1
            ;;
        \?)
            usage
            ;;
    esac
done

[ "${INITIALISE}" -eq 1 ] && initialise

if [ "${AUTOFIX}" -eq 1 ]; then
    if [ "${subscribed}" -eq 1 ]; then
        ls ${ENTITLEMENTCERTDIR}/*.pem &> /dev/null
        if [ "$?" -ne 0 ]; then
            fix_cert
        fi

        if [ ! -e "${MASTERREPOCONF}" -o -e "${SMREPOCONF}" ]; then
            TEMPFILE=$(mktemp)
            NEWCERT=$(find ${ENTITLEMENTCERTDIR} -newer ${TEMPFILE})
            fix_cert
            [ "${NEWCERT}X" != "X" ] && echo "New certificate(s) detected: ${NEWCERT}"
            \rm ${TEMPFILE} &> /dev/null
            configure_master_repo
        fi

        [ "${REPOSDIR}X" != "X" ] && ln -sf ${MASTERREPOCONF} ${REPOSDIR}/${MASTERREPO}
    fi
else
    sanity_check
fi

[ "${UPDATE}" != 1 -a "${GENREPO}" != 1 ] && exit 0

[ "${DISTRO}" != "" ] && DISTROS="${DISTRO//,/ }"
[ "${REPO}" != "" ] && REPOS="${REPO//,/ }"

if [ "${DISTROS}" == "" ]; then
    if [ "${REPOS}" == "" ]; then
        process_distro_repo
    else
        for TREPO in ${REPOS}; do
            process_distro_repo
        done
    fi
else
    for TDISTRO in ${DISTROS}; do
        if [ "${REPOS}" == "" ]; then
            process_distro_repo
        else
            for TREPO in ${REPOS}; do
                process_distro_repo
            done
        fi
    done
fi
