#!/usr/bin/env python

import ConfigParser
import sys

def usage():
    sys.stderr.write('Usage: %s <config file>\n\n' % sys.argv[0].split('/')[-1])
    sys.exit(1)

def read_conf(config):
    parser = ConfigParser.SafeConfigParser()
    
    try:
        parser.read(config)
    except:
        sys.stderr.write('Error reading %s.\n' % config)
        sys.exit(1)

    try:
        control_opts = parser.items('control')
    except:
        sys.stderr.write('Missing [control] section in %s.\n' % config)
        sys.exit(1)

    try:
        repolist = parser.items('repos')
    except:
        sys.stderr.write('Missing [repos] section in %s.\n' % config)
        sys.exit(1)

    for opt,val in control_opts:
        print '%s=%s' % (opt, val)

    opts=[]
    vals=[]
    for opt,val in repolist:
        opts.append(opt)
        vals.append(val)

    print 'repostore=(%s)' % ' '.join(opts)
    print 'reponame=(%s)' % ' '.join(vals)
    
if __name__ == '__main__':
    if len(sys.argv) < 2:
        usage()

    read_conf(sys.argv[1])
    
