#!/bin/bash

usage() {
    echo "Usage: $(basename $0) <version> <kind> <arch>"
    echo "example:"
    echo -e "\t$(basename $0) 5 Server x86_64"
    exit 1
}

[ "$#" -lt 3 ] && usage

VERSION=$1
KIND=$2
ARCH=$3

MASTERREPOCONF="/etc/yum.repos.d/master.repo"

if [ ! -e ${MASTERREPOCONF} ]; then
    echo "${MASTERREPOCONF} is missing. No usable base repo configuration file."
    exit 1
fi

sed -e "s:/[1-9]/:/$VERSION/:" -e "s:/[1-9][a-Z]\+/:/$VERSION$KIND/:" -e "s:\$releasever:$VERSION$KIND:" -e "s:\$basearch:$ARCH:" -e "s:-[1-9]-:-$VERSION-:" -e "s: [1-9] : $VERSION :" ${MASTERREPOCONF}

