#!/usr/bin/env python

import ConfigParser
import sys

def usage():
    sys.stderr.write('Usage: %s <config file> <section>\n\n' % sys.argv[0].split('/')[-1])
    sys.exit(1)

def read_conf(config, section):
    parser = ConfigParser.SafeConfigParser()

    try:
        parser.read(config)
    except:
        sys.stderr.write('Error reading %s.\n' % config)
        sys.exit(1)

    try:
        opts = parser.items(section)
    except:
        sys.stderr.write('Missing section %s in %s.\n' % (section,config))
        sys.exit(1)

    for opt,val in opts:
        print '%s=%s' % (opt, val)


if __name__ == '__main__':
    if len(sys.argv) < 3:
        usage()

    read_conf(sys.argv[1], sys.argv[2])

